[2024-11-08T03:09:51.784+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-08T03:09:51.851+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_etl_postgres.load_to_postgres manual__2024-11-08T02:09:46.480371+00:00 [queued]>
[2024-11-08T03:09:51.880+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_etl_postgres.load_to_postgres manual__2024-11-08T02:09:46.480371+00:00 [queued]>
[2024-11-08T03:09:51.881+0100] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-08T03:09:51.926+0100] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-11-08 02:09:46.480371+00:00
[2024-11-08T03:09:51.932+0100] {standard_task_runner.py:72} INFO - Started process 18092 to run task
[2024-11-08T03:09:51.940+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test_etl_postgres', 'load_to_postgres', 'manual__2024-11-08T02:09:46.480371+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp0gz3sqew']
[2024-11-08T03:09:51.944+0100] {standard_task_runner.py:105} INFO - Job 3: Subtask load_to_postgres
[2024-11-08T03:09:52.191+0100] {task_command.py:467} INFO - Running <TaskInstance: test_etl_postgres.load_to_postgres manual__2024-11-08T02:09:46.480371+00:00 [running]> on host DESKTOP-SO44L49.
[2024-11-08T03:09:52.485+0100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_etl_postgres' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-08T02:09:46.480371+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-08T02:09:46.480371+00:00'
[2024-11-08T03:09:52.489+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-08T03:09:52.490+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-08T03:09:52.491+0100] {logging_mixin.py:190} INFO - Current task name:load_to_postgres state:running start_date:2024-11-08 02:09:51.852338+00:00
[2024-11-08T03:09:52.492+0100] {logging_mixin.py:190} INFO - Dag name:test_etl_postgres and current dag run status:running
[2024-11-08T03:09:52.492+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-08T03:09:52.559+0100] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-08T03:09:54.631+0100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow/dags/test.py", line 20, in load_to_postgres
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2024-11-08T03:09:54.697+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-08T03:09:54.697+0100] {logging_mixin.py:190} INFO - Task start:2024-11-08 02:09:51.852338+00:00 end:2024-11-08 02:09:54.696413+00:00 duration:2.844075
[2024-11-08T03:09:54.698+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_postgres> dag:<DAG: test_etl_postgres> dagrun:<DagRun test_etl_postgres @ 2024-11-08 02:09:46.480371+00:00: manual__2024-11-08T02:09:46.480371+00:00, state:running, queued_at: 2024-11-08 02:09:46.532120+00:00. externally triggered: True>
[2024-11-08T03:09:54.698+0100] {logging_mixin.py:190} INFO - Failure caused by could not translate host name "postgres" to address: Name or service not known
[2024-11-08T03:09:54.699+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_etl_postgres, task_id=load_to_postgres, run_id=manual__2024-11-08T02:09:46.480371+00:00, execution_date=20241108T020946, start_date=20241108T020951, end_date=20241108T020954
[2024-11-08T03:09:54.732+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-08T03:09:54.732+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 3 for task load_to_postgres (could not translate host name "postgres" to address: Name or service not known
; 18092)
Traceback (most recent call last):
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow/dags/test.py", line 20, in load_to_postgres
    conn = pg_hook.get_conn()
           ^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Name or service not known

[2024-11-08T03:09:54.778+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-08T03:09:54.936+0100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-08T03:09:54.944+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
