[2024-11-09T02:46:00.007+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-09T02:46:00.037+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_postgres_load.load_to_postgres manual__2024-11-09T01:45:52.928897+00:00 [queued]>
[2024-11-09T02:46:00.048+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_postgres_load.load_to_postgres manual__2024-11-09T01:45:52.928897+00:00 [queued]>
[2024-11-09T02:46:00.049+0100] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-09T02:46:00.064+0100] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-11-09 01:45:52.928897+00:00
[2024-11-09T02:46:00.068+0100] {standard_task_runner.py:72} INFO - Started process 91855 to run task
[2024-11-09T02:46:00.071+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgres_load', 'load_to_postgres', 'manual__2024-11-09T01:45:52.928897+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpi1ucak_h']
[2024-11-09T02:46:00.072+0100] {standard_task_runner.py:105} INFO - Job 13: Subtask load_to_postgres
[2024-11-09T02:46:00.162+0100] {task_command.py:467} INFO - Running <TaskInstance: etl_postgres_load.load_to_postgres manual__2024-11-09T01:45:52.928897+00:00 [running]> on host DESKTOP-SO44L49.
[2024-11-09T02:46:00.278+0100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_postgres_load' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-09T01:45:52.928897+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-09T01:45:52.928897+00:00'
[2024-11-09T02:46:00.280+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-09T02:46:00.280+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-09T02:46:00.280+0100] {logging_mixin.py:190} INFO - Current task name:load_to_postgres state:running start_date:2024-11-09 01:46:00.037697+00:00
[2024-11-09T02:46:00.281+0100] {logging_mixin.py:190} INFO - Dag name:etl_postgres_load and current dag run status:running
[2024-11-09T02:46:00.281+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-09T02:46:00.306+0100] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2024-11-09T02:46:00.360+0100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow/dags/test.py", line 45, in load_to_postgres
    with open(file_path, 'r') as csv_file:
         ^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/home/hajar/airflow/data/transformed_train.csv/part-00000-7cd1c74a-d466-4da6-a118-89ca817afd4c-c000.csv/'
[2024-11-09T02:46:00.398+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-09T02:46:00.399+0100] {logging_mixin.py:190} INFO - Task start:2024-11-09 01:46:00.037697+00:00 end:2024-11-09 01:46:00.397966+00:00 duration:0.360269
[2024-11-09T02:46:00.399+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_to_postgres> dag:<DAG: etl_postgres_load> dagrun:<DagRun etl_postgres_load @ 2024-11-09 01:45:52.928897+00:00: manual__2024-11-09T01:45:52.928897+00:00, state:running, queued_at: 2024-11-09 01:45:52.982536+00:00. externally triggered: True>
[2024-11-09T02:46:00.399+0100] {logging_mixin.py:190} INFO - Failure caused by [Errno 20] Not a directory: '/home/hajar/airflow/data/transformed_train.csv/part-00000-7cd1c74a-d466-4da6-a118-89ca817afd4c-c000.csv/'
[2024-11-09T02:46:00.399+0100] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_postgres_load, task_id=load_to_postgres, run_id=manual__2024-11-09T01:45:52.928897+00:00, execution_date=20241109T014552, start_date=20241109T014600, end_date=20241109T014600
[2024-11-09T02:46:00.421+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-09T02:46:00.422+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task load_to_postgres ([Errno 20] Not a directory: '/home/hajar/airflow/data/transformed_train.csv/part-00000-7cd1c74a-d466-4da6-a118-89ca817afd4c-c000.csv/'; 91855)
Traceback (most recent call last):
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hajar/airflow/dags/test.py", line 45, in load_to_postgres
    with open(file_path, 'r') as csv_file:
         ^^^^^^^^^^^^^^^^^^^^
NotADirectoryError: [Errno 20] Not a directory: '/home/hajar/airflow/data/transformed_train.csv/part-00000-7cd1c74a-d466-4da6-a118-89ca817afd4c-c000.csv/'
[2024-11-09T02:46:00.445+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-09T02:46:00.500+0100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-09T02:46:00.503+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
